### ISSUE TITLE
FastBoot failing with Ember 2.9

### ISSUE THREAD

**Issue by bcardarella** [ember-fastboot/ember-cli-fastboot#266]
Not a duplicate of #265 

Deploying our staging server with built assets: https://staging.dockyard.com/

A previously working Ember app in Fastboot is now failing. The error is clearly in vendor.js but because I cannot run the fastboot server on my machine due to #265 I cannot diagnose the issue.

**Comment by danmcclain** [comment]
> Not a duplicate of #265 
Passive aggressiveness not appreciated

**Comment by bcardarella** [comment]
> Passive aggressiveness not appreciated

It has a similarly named issue title and I wanted to draw attention to this.

**Comment by bcardarella** [comment]
Stacktrace I'm seeing:

```
TypeError: n.get(...).getURL is not a function at [object Object]. (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:11:18665) at o.m.get (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:8:30397) at Object.n [as get] (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:10:6954) at [object Object].a.default.extend.getURL (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:5:2198) at Result._finalizeMetadata (/home/production/dockyard-app-server/node_modules/fastboot/lib/result.js:74:25) at Result._finalize (/home/production/dockyard-app-server/node_modules/fastboot/lib/result.js:64:12) at /home/production/dockyard-app-server/node_modules/fastboot/lib/ember-app.js:225:26 at C (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:21:11181) at k (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:21:11267) at x (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:21:11084) at /home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:13:29447 at s.invokeWithOnError (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:9653) at Object.s.flush (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:10096) at Object.u.flush (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:10866) at Object.d.end (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:11211) at [object Object]._onTimeout (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:8437) at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by danmcclain** [comment]
Are you getting the URL from the router at any point in fastboot?

**Comment by danmcclain** [comment]
Also, Ember/glimmer2 works with 2.9 according to: https://github.com/emberjs/ember.js/issues/13949 (Scroll down to addons/tooling). This is likely application issue, or an issue with a specific addon. I would try to run an non-uglified version of the code on staging to debug

**Comment by danmcclain** [comment]
I could still be a fastboot issue, but getURL hints that you may be accessing something from the router that isn't available

**Comment by bcardarella** [comment]
I am looking into it, but as I previously mentioned in #265 the application has not changed beyond updating the ember and ember-data deps.

**Comment by bcardarella** [comment]
Updating `fastboot-app-server` seems to have cleared the issue. However, now the app is not rendering server-side.

**Comment by bcardarella** [comment]
Its strange, I'm not seeing any errors in the app-server logs

**Comment by danmcclain** [comment]
Are you still running the same NGINX config since before I left, NGINX is swallowing the errors if so

**Comment by bcardarella** [comment]
No, I rewrote everything. I can see the requests being handled by the app server:

```
[2016-09-19T00:47:28.068Z][w23698] starting HTTP server
[2016-09-19T00:47:28.077Z][w23698] HTTP server started; url=http://:::3000
2016-09-19T00:47:37.909Z 200 OK /
2016-09-19T00:48:10.436Z 200 OK /
2016-09-19T00:50:20.157Z 200 OK /services
2016-09-19T00:50:58.564Z 200 OK /services
2016-09-19T00:54:40.107Z 200 OK /
2016-09-19T00:56:40.126Z 200 OK /
```

and it seems to indicate that the app is being served just fine which means that Nginx shouldn't be seeing any errors as the app server is not reporting any errors. However, the version of the app being served is clearly not server-side rendered. Simple things like the `title` tag is also not rendering but I suspect this is likely a Glimmer 2 issue and not related to Fastboot at all.

**Comment by danmcclain** [comment]
Do you have `resilient mode` turned on in the fastboot-express-middleware

**Comment by bcardarella** [comment]
If that is something I have to opt-into then I would saw I do not have that turned on. Our app server is here: https://github.com/DockYard/dockyard-app-server

**Comment by danmcclain** [comment]
It's on by default in `fastboot-app-server`, [resilient mode](https://github.com/ember-fastboot/fastboot-express-middleware#resilient-mode)

**Comment by bcardarella** [comment]
Ok, after disabling `resilient: true` on the app server I now see a new error:

```
2016-09-19T01:14:32.909Z 500 Unknown Error: Error: Assertion Failed: EventDispatcher should never be instantiated in fastboot mode. Please report this as an Ember bug.
    at /home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:5:24700
    at Object.n [as assert] (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:9:92)
    at [object Object].e.default.n.Object.extend.init (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:14:24261)
    at [object Object].r [as init] (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:14:12794)
    at new o (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:13:12704)
    at Function.m.create (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:13:14949)
    at f (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:19412)
    at a (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:17606)
    at Object.i.lookup (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:21391)
    at [object Object].e.default.t.Mixin.create.lookup (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:12:22350)
    at /home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:6:2494
    at [object Object].r.CoreView.extend.u.init (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:6:2614)
    at [object Object].r [as init] (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:14:12794)
    at new o (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:13:12704)
    at Function.m.create (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:13:14949)
    at Object.t [as initialize] (/home/production/dockyard-app-server/current/fastboot/dockyard-488f3b085f4a6914dac19c5358864c0e.js:4:28360)
    at /home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:5:15963
    at e.each (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:30926)
    at e.topsort (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:30421)
    at e.topsort (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:29829)
    at [object Object].r.Namespace.extend._runInitializer (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:5:16142)
    at [object Object].r.Namespace.extend.runInstanceInitializers (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:5:15854)
    at [object Object].a.default.extend._bootSync (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:5:1328)
    at /home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:5:10190
    at D (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:21:11447)
    at new I (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:21:13078)
    at [object Object].r.Object.extend.boot (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:5:10148)
    at /home/production/dockyard-app-server/node_modules/fastboot/src/ember-app.js:219:25
    at C (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:21:11181)
    at k (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:21:11267)
    at x (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:21:11084)
    at /home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:13:29447
    at s.invokeWithOnError (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:9653)
    at Object.s.flush (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:10096)
    at Object.u.flush (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:10866)
    at Object.d.end (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:11211)
    at [object Object]._onTimeout (/home/production/dockyard-app-server/current/fastboot/vendor-e66ac5437cda24ede6b1afcff0ec4633.js:4:8437)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by rwjblue** [comment]
Sorry, lots of comments and I may have missed where you mentioned it, but what is the Ember.VERSION being used?

**Comment by rwjblue** [comment]
Generally, when I see that event dispatcher error its because something isn't properly honoring the `app.visit` flags that we pass in in `fastboot`.  But there have been a number of bugs around this area since 2.9.0-beta.1, and it could be something that was fixed upstream (depending on Ember version).  I would test with latest published `beta` build to ensure you have the most up to date one.

**Comment by bcardarella** [comment]
@rwjblue our app is out Ember 2.9.0-beta.2 with Ember Data 2.9.0-beta.1

**Comment by martndemus** [comment]
@rwjblue I can confirm it's still happening with `2.9.0-beta.3` and `2.10.0-canary+6ea3ed0c`.

**Comment by martndemus** [comment]
This issue can be closed. https://github.com/emberjs/ember.js/issues/14333#issuecomment-248933438

**Comment by bcardarella** [comment]
@martndemus thanks!

**Comment by rwwagner90** [comment]
I'm seeing this issue still. How do I fix it? On Ember and Ember CLI version 2.10 beta
